# Generated by Django 1.11.27 on 2020-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="locations",
            field=models.ManyToManyField(to="common.Location"),
        ),
    ]
