# Generated by Django 1.11.27 on 2020-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_set_default_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="title",
            field=models.TextField(null=True, verbose_name="Title"),
        ),
    ]
