# Generated by Django 3.2.13 on 2022-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_auto_20210314_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="url",
            field=models.URLField(default="", verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="group",
            name="url",
            field=models.URLField(default="", verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="room",
            name="url",
            field=models.URLField(default="", max_length=500, verbose_name="URL"),
        ),
    ]
