# Generated by Django 3.2.25 on 2025-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_update_url_type_to_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='stream',
            field=models.TextField(null=True, verbose_name='Stream'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='summary',
            field=models.TextField(null=True, verbose_name='Summary'),
        ),
    ]
