# Generated by Django 3.2.25 on 2025-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_add_summary_and_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_modified',
            field=models.DateTimeField(null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_modified',
            field=models.DateTimeField(null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='last_modified',
            field=models.DateTimeField(null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
