# Generated by Django 3.2.25 on 2025-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_add_last_modified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["course"], name="common_exam_course__c5a86c_idx"
            ),
        ),
    ]
