# Generated by Django 3.2.25 on 2025-08-25 10:53

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_add_subscription_added_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(django.db.models.functions.text.Upper('alias'), name='common_subs_alias_upper_idx'),
        ),
    ]
