# Generated by Django 3.2.25 on 2026-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="last_modified",
            field=models.DateTimeField(null=True, verbose_name="Last modified"),
        ),
        migrations.AddField(
            model_name="semester",
            name="version",
            field=models.BigIntegerField(default=0, verbose_name="Version"),
        ),
    ]
