# Generated by Django 5.2.14 on 2026-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_auto_20260507_2133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="code",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Code"
            ),
        ),
    ]
