[project]
authors = [{ name = "Thomas Adamcik", email = "thomas@adamcik.no" }]
license = { text = "AGLv3" }
requires-python = "<4.0,>=3.9"
dependencies = [
  "Django~=3.2.12",
  "django-compressor~=2.4",
  "lxml~=4.6.3",
  "psycopg2~=2.8.6",
  "requests~=2.25.1",
  "tqdm",
  "typing-extensions>=4.12.2",
  "vobject~=0.9.6.1",
]
name = "plan"
version = "2.0.0"
readme = "README.md"
description = "Timetable generator for educational institutions."

[project.urls]
repository = "https://github.com/adamcik/plan"

# TODO: Is this needed?
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "django-stubs~=4.2.7",
]
