# Generated by Django 3.2.25 on 2025-08-29 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW materialized_semester_analytics AS
            SELECT
                c.semester_id,
                COUNT(DISTINCT c.id) AS num_courses,
                COUNT(DISTINCT s.student_id) AS num_unique_students,
                COUNT(s.id) AS num_subscriptions
            FROM
                common_course AS c
            LEFT JOIN
                common_subscription AS s ON c.id = s.course_id
            GROUP BY
                c.semester_id
            ORDER BY
                c.semester_id ASC
            WITH DATA;
            """,
            reverse_sql="""
            DROP MATERIALIZED VIEW materialized_semester_analytics;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX materialized_semester_analytics_semester_id_idx
                ON materialized_semester_analytics(semester_id);
            """,
            reverse_sql="""
            DROP INDEX materialized_semester_analytics_semester_id_idx;
            """,
        ),
    ]
