# Generated by Django 3.2.25 on 2025-08-29 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materialized", "0001_semester_analytics_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW materialized_top_courses AS
            SELECT
                c.semester_id,
                c.id AS course_id,
                c.code AS course_code,
                c.name AS course_name,
                COUNT(u.id) AS subscription_count,
                ROW_NUMBER() OVER (PARTITION BY c.semester_id ORDER BY COUNT(u.id) DESC) AS rank
            FROM
                common_subscription AS u
            JOIN
                common_course AS c ON u.course_id = c.id
            GROUP BY
                c.semester_id,
                c.id,
                c.code,
                c.name
            ORDER BY
                c.semester_id ASC,
                subscription_count DESC
            WITH DATA;
            """,
            reverse_sql="""
            DROP MATERIALIZED VIEW materialized_top_courses;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX materialized_top_courses_semester_course_idx
                ON materialized_top_courses(semester_id, course_id);
            """,
            reverse_sql="""
            DROP INDEX  materialized_top_courses_semester_course_idx;
            """,
        ),
    ]
