# Generated by Django 3.2.25 on 2025-08-29 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materialized", "0002_top_courses_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW materialzed_subscriptions_count AS
            SELECT
                COUNT(*) AS count,
                date
            FROM (
                SELECT
                    CAST(MIN(s.added) AS DATE) AS date,
                    student_id,
                    semester_id
                 FROM common_subscription s
                 JOIN common_course c ON (c.id = s.course_id)
                 GROUP BY student_id, semester_id
             ) AS query
             GROUP BY date
             ORDER BY date ASC
            WITH DATA;
            """,
            reverse_sql="""
            DROP MATERIALIZED VIEW materialzed_subscriptions_count;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX materialzed_subscriptions_count_date_idx ON
                materialzed_subscriptions_count (date);
            """,
            reverse_sql="""
            DROP INDEX materialzed_subscriptions_count_date_idx;
            """,
        ),
    ]
