# Generated by Django 3.2.25 on 2025-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("materialized", "0003_subscriptions_count_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterAnalytics",
            fields=[
                ("semester_id", models.IntegerField(primary_key=True, serialize=False)),
                ("num_courses", models.IntegerField()),
                ("num_unique_students", models.IntegerField()),
                ("num_subscriptions", models.IntegerField()),
            ],
            options={
                "db_table": "materialized_semester_analytics",
                "ordering": ["semester_id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionsCount",
            fields=[
                ("count", models.IntegerField()),
                ("date", models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "materialzed_subscriptions_count",
                "ordering": ["date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TopCourses",
            fields=[
                ("semester_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
                ("course_code", models.CharField(max_length=100)),
                ("course_name", models.TextField()),
                ("subscription_count", models.IntegerField()),
                ("rank_in_semester", models.IntegerField()),
                ("django_pk", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "materialized_top_courses",
                "ordering": ["semester_id", "-subscription_count"],
                "managed": False,
            },
        ),
    ]
