name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run nix fmt
        run: nix fmt

      - name: Run nix flake check
        run: nix flake check

      - name: Build image
        run: nix build .#image

      - name: Login to GHCR
        # if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: echo "${{ github.token }}" | skopeo login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image to GHCR
        # if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: nix run .#image.copyToRegistry
