name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/workflow.yml
    with:
      mode: ci
      publish_main: ${{ github.event_name == 'push' }}
    secrets: inherit
